server:
  port: 8073
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
  
spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_NAME:easybuy}
        databaseName:
        serverName:
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:1234}
        connectionTimeout: 10000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true