server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: buyer-service 
          uri: lb://buyer-service
          predicates:
          - Path=/api/products/**,/api/products/categories/**,/api/products/add_to_cart/**,/api/products/{id}/**
 
          